### ISSUE TITLE
Reorganizing scripts

### ISSUE THREAD

**Issue by centipeda** [centipeda/soc-benchmark#10]
Now that we're expanding the scope of the benchmarks to possibly include networking, CPU monitoring, etc., it would be good to re-examine how the repository is structured right now. Functionality is split between a lot of different scripts in different directories at the moment, and not really in a way that makes sense. 

I'll start by consolidating each of the benchmark scripts and revising the main script to be a little more failure-resistant. Ideally, it'll be possible for people to clone and run these benchmarks with little tweaking required.

**Comment by bobby-schiller** [comment]
Oliver gave some general comments about the usability of the benchmarking suite:

> I would have a few additional remarks to the benchmarking suite. To me it was a bit hard to understand the organization of files in the repository. For example, I checked out the repo and found the script is checking out the repository again in another subfolder. Also moving the script files should be avoided. Better copy. I would also suggest some convenience options. The result summaries should be copied/moved to a results folder and have meaningful names including the benchmark, date, architecture and the like.
>  
> Don’t get me wrong. It is a good start.

The first comment is related to the fact that the main script is written to work even if it is the only part of the repo copied to the host machine. I also forgot this recently and understand why it can be confusing; we should consider rewriting the script to assume the entire repo is cloned (since I think this is the most likely use case). The other two comments make sense as well, and should be easy to implement. Thoughts?

**Comment by centipeda** [comment]
That makes sense, I was thinking along the same lines. I've pushed some of the changes I've already made to a new branch.

**Comment by centipeda** [comment]
The linked pull request includes my working changes so far. I've implemented Oliver's suggestions, and a few other things I thought might make the process cleaner and easier to understand.

The script compiles and runs the benchmarks from where they are in `benchmark_src`, without copying (with the exception of Coremark, which pulls from the GitHub repo when the script is first run. I'm still on the fence about doing that instead of just copying the Coremark source). The script also cleans the source directory before exiting. 

All the recorded results have been consolidated into their own folders. When the script is run, all the results appear in a new folder named, by default, `${hostname}_results_${date}_${time}`. Each set of results appears in that folder in a file named, for example, `coremark.txt` or `whetstone.txt`. It also creates a summary file named `results_summary.txt`. 

Instead of editing Makefiles with `sed` to alter arguments to the compiler, which seemed brittle, the script now just overrides the appropriate variables as it calls `make`, e.g., 
```
make -C $SRC_DIR/whetstone CFLAGS="-O3 -Ofast ..." whetstone
```

The package check is now disabled by default unless a command-line flag is passed in (`--check-pkg`).

The hardware monitoring part was mostly left untouched and doesn't really work, but that's because I figure it'll be replaced by `iostat` fairly soon.

**Comment by bobby-schiller** [comment]
Structural changes all look good. It's definitely easier to follow the repository structure now. It looks like some of the flags for Coremark got lost, though (specifically the multithreading and the `-03` optimization). I am pushing some changes to restore those flags and also automatically detect the number of threads.

Sorry for the delay on the HW monitoring, `pidstat` is giving me some problems. The logic works but `pidstat` always reports 0% CPU usage. Do you know if `top` is available on your build?

**Comment by centipeda** [comment]
Thanks, I missed that.

Yes, I have `top` on my build.
