### ISSUE TITLE
Renaming to soc-benchmark

### ISSUE THREAD

**Issue by centipeda** [centipeda/soc-benchmark#9]
Since the scope of this repository has expanded to benchmarking arbitrary processors and SoCs, I thought it might be better named something like `soc-benchmark`. There are concerns about link rot, though, since the current name of the repository has already been hardlinked in documents.

From [this post](https://github.community/t5/How-to-use-Git-and-GitHub/How-long-does-github-forward-renamed-moved-repos/td-p/3256), it seems like GitHub will indefinitely redirect renamed repositories as long as a new one isn't created with the old name.

The other option is to create a new repository with the new name, and to redirect users to the new repository in this one. The only disadvantage that I can see of this approach is losing the commit and issue history of this repository.

Thoughts?

**Comment by bobby-schiller** [comment]
I'm in favor of just renaming this repository. I confirmed that the link forwarding works with one of my own repositories and I think it would be best to maintain the commit/issue histories.

**Comment by centipeda** [comment]
Done. If it causes issues in the future, we can just create the new repo.
